#! /bin/bash

set -o errexit

image=srp33/$(basename $(pwd))
tag=version$(cat VERSION)

src/helper/build_commands $tag

docker build -t $image:$tag .

##docker login -u=$(dirname $image)
#docker push srp33/jicama
