#! /bin/bash

set -o errexit

#tmpDir=/tmp/somatic-wgs-build

#mkdir -p $tmpDir
#rm -rf $tmpDir/*

#cp -v Dockerfile $tmpDir
#cp -v *.sh $tmpDir
#cp -v *.py $tmpDir
#cp -v LICENSE $tmpDir
#cp -v README.md $tmpDir

#cd $tmpDir
docker build -t srp33/somatic_wgs:version$(cat VERSION) .

#docker run -i -t --rm srp33/somatic_wgs:version$(cat VERSION) /bin/bash
