#! /bin/bash

tag=$1

mkdir -p bin docs
rm -f bin/* docs/*

for f in src/command_meta/*.yaml
do
    out_f=$(basename $f)
    out_f=${out_f/\.yaml/}
    out_f=bin/${out_f}
    help_f=docs/$(basename $out_f)

    python3 src/helper/build_commands.py $f $tag ${out_f} ${help_f}
done

chmod 777 bin docs
chmod 777 bin/* docs/*
