#! /bin/bash

source usage_functions
source check_functions

set -o errexit

VCF_URL=Null
DICT_FILE=Null
VERSION_LOG=""
ARGNUM=$#

for (( i=1; i<=ARGNUM; i++ )); do
  OPTARG=$((i+1))
  case "${!i}" in
    -u | --vcf_url )
      check_args "${!OPTARG}" "${!i}" || exit 1
      VCF_URL="${!OPTARG}"
      i=$((i+1))
      ;;
    -d | --dict_file )
      check_args "${!OPTARG}" "${!i}" || exit 1
      DICT_FILE="${!OPTARG}"
      i=$((i+1))
      ;;
    --log )
      check_args "${!OPTARG}" "${!i}" || exit 1
      VERSION_LOG="${!OPTARG}"
      i=$((i+1))
      ;;
    -h | --help )
      usage_prep_recal_vcf
      exit 0
      ;;
    * )
      echo "Invalid option: ${!i}" 1>&2
      exit 1
      ;;
  esac
done

MISSING_VOLUMES=()
EXIT_CODE=0

[[ ${VCF_URL} != "Null" ]] || { echo "
ERROR: VCF URL (-u <arg>) argument must be provided" && \
 usage_prep_recal_vcf && exit 1; }
[[ ${DICT_FILE} != "Null" ]] || { echo "
ERROR: DICT_FILE (-d <arg>) argument must be provided" && \
 usage_prep_recal_vcf && exit 1; }

[[ -d /data/ref_index ]] || { MISSING_VOLUMES+=(/data/ref_index) && EXIT_CODE=1; }
[[ -d /data/output_data ]] || { MISSING_VOLUMES+=(/data/output_data) && EXIT_CODE=1; }

if [[ ${EXIT_CODE} = 1 ]]; then
    echo "
    The following volumes are missing: ${MISSING_VOLUMES[@]}" && echo_usage && exit 1
fi

python /check_permissions.py /data/ref_index ReadWrite || exit 1
python /check_permissions.py /data/output_data ReadWrite || exit 1

VCF_FILE=/tmp/"$(basename ${VCF_URL/\.gz/})" \
TMP_FILE=/tmp/"$(basename ${VCF_FILE}).2" \
OUT_FILE=/data/output_data/"$(basename ${VCF_FILE})"

wget -O "${VCF_FILE}.gz" "${VCF_URL}"
gunzip "${VCF_FILE}.gz"

python /reconcile_vcf_with_dict.py "${VCF_FILE}" /data/ref_index/"${DICT_FILE}" "${TMP_FILE}"

picard -Xms512m -Xmx8g SortVcf \
    I="${TMP_FILE}" \
    O="${OUT_FILE}" \
    SEQUENCE_DICTIONARY=/data/ref_index/"${DICT_FILE}" \
    CREATE_INDEX=true
